---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: httpd-deployment
  labels:
    app: webserver
    author: raju
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      name: httpd-pod
      labels: 
        app: webserver
    spec:    
      containers:
        - name: myhttpd
          image: httpd
          ports:
            - containerPort: 80
              hostPort: 8080
...
