---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: jenkins-deployment
  labels: 
    app: myjenkins
    author: raju
spec: 
  replicas: 3
  selector: 
    matchLabels:
      app: myjenkins
  template:
    metadata:
      name: jenkins-pod
      labels: 
         app: myjenkins
    spec:
      containers:
        - name: jenkins
          image: jenkins/jenkins
          ports: 
            - containerPort: 8080
              hostPort: 9090
...
