---
apiVersion: v1
kind: Pod
metadata: 
  name: wordpress-pod
  labels:
    app: data
    author: raju
spec:
  containers:
    - name: wordpress-raju
      image: wordpress
      env:
      - name: WORDPRESS_DB_PASSWORD
        value: raju
      - name: WORDPRESS_DB_USER
        value: myuser
      - name: WORDPRESS_DB_HOST
        value: wordpress-pod
      - name: WORDPRESS_DB_NAME
        value: mydb

...
