
apiVersion: v1
kind: Pod
metadata: 
  name: mysql-pod
  labels:
    app: mysql-image
    author: raju 
spec:
  containers:
    - name: mysql-container
      image: mysql
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: raju

