---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: proxy
    author: raju
spec:
  containers:
    - name: mynginx
      image: nginx
      ports:
        - containerPort: 80
          hostPort: 3030
...
