--- 
apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: ghost-rs
  labels: 
    type: html
    author: raju
spec:
  replicas: 2
  selector:
    matchLabels: 
      type: html
  template:
     metadata:
       name: ghost-pod
       labels: 
         type: html
     spec:
       containers:
          - name: ghost
            image: ghost
            ports: 
             - containerPort: 80
               hostPort: 9089
...
