---
apiVersion: v1 
kind: ReplicationController
metadata:
  name: mysql-rc
  labels:
    type: mydb
    author: raju
spec:
  replicas: 2
  template:
    metadata:
      labels: 
        type: mydb
    spec:
      containers:
        - name: mysql-raju
          image: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD 
              value: raju
            - name: MYSQL_USER
              value: myuser
            - name: MYSQL_DATABASE
              value: mydb

...
